### PR TITLE
fix before_filter deprecation

### PR DESCRIPTION
**Pull request by petitJAM**

### CODE REVIEW

**Comment by boatrite** [comment]
:boat:

**Comment by petitJAM** [comment]
do we have any projects using jefferies_tube on Rails 3 still? This breaks Rails 3 compatibility.  Rails 5.1 will remove `before_filter` though, so we'll need to cut this over eventually or actually start versioning/releasing this thing.

**Comment by boatrite** [comment]
Good catch. I thought before_action was added in rails 3, but it's rails 4. Are crantastic/cis rails 3 projects? uwle might also be 3. I forget all that we've upgraded to 4. You'll probably have to crawl through the Gemfiles to check.

**Comment by petitJAM** [comment]
Is there a reason this isn't on rubygems? @samsonasu

**Comment by samsonasu** [comment]
fixed by #20

**Pull request closed without merging**
